# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_auto_20170528_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
    ]
