# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productfeatured'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeatured',
            name='make_image_carousel',
            field=models.BooleanField(default=False),
        ),
    ]
