# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_categoryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='color',
            new_name='title',
        ),
    ]
