# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20170526_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryimage',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_set', to='products.Category'),
            preserve_default=False,
        ),
    ]
