# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_categoryimage_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryimage',
            name='product',
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
    ]
